// Seed activities for the /things-to-do page
import { PrismaClient } from "@prisma/client"
const db = new PrismaClient()

async function destId(slug: string) {
  const d = await db.destination.findUnique({ where: { slug }, select: { id: true } })
  return d?.id ?? null
}

const activities = [
  { slug: "gondola-ride-gulmarg", title: "Gulmarg Gondola — World's Highest Cable Car", category: "adventure", shortDescription: "Ride the iconic Gulmarg Gondola to 4,000m on Apharwat Peak — one of the highest cable cars on Earth with panoramic Himalayan views.", description: "The Gulmarg Gondola is among the world's highest cable cars, climbing from Gulmarg (2,690m) to Apharwat Peak (4,000m) in two stages. The views from the top span from Nanga Parbat to the Himalayan range. In winter it accesses legendary powder skiing; in summer it offers alpine meadows and snow patches even in July. The gondola was built by POMA (France) and operates year-round weather permitting.", images: [], duration: "1-2 hours", difficulty: "Easy", bestSeason: "Year-round (snow in winter, meadows in summer)", destSlug: "gulmarg", metaTitle: "Gulmarg Gondola Ride — World's Highest Cable Car to 4,000m", metaDescription: "Ride the Gulmarg Gondola to Apharwat Peak (4,000m) — one of the highest cable cars on Earth. Book with Asgari Tour & Travels.", featured: true, order: 1 },
  { slug: "shikara-ride-dal-lake", title: "Sunrise Shikara Ride on Dal Lake", category: "leisure", shortDescription: "Glide across Dal Lake at dawn on a traditional shikara — past floating gardens, the flower market, and snow-capped peaks reflected in the water.", description: "The dawn shikara ride on Dal Lake is among Asia's most photographed experiences. Your boatman rows past floating vegetable gardens, the floating flower market (open 5-7am), and the chinar-lined boulevards, with the Pir Panjal range turning gold behind the water. Shikaras can seat 2-6 people and the ride lasts 1-2 hours. Sunset rides are equally magical.", images: [], duration: "1-2 hours", difficulty: "Easy", bestSeason: "April to October", destSlug: "dal-lake", metaTitle: "Shikara Ride on Dal Lake Srinagar — Dawn & Sunset", metaDescription: "Traditional shikara ride on Dal Lake at dawn or sunset. Floating market, gardens, snow-peak reflections. Book with Asgari Tours.", featured: true, order: 2 },
  { slug: "powder-skiing-gulmarg", title: "Gulmarg Powder Skiing & Snowboarding", category: "adventure", shortDescription: "Ski legendary Himalayan powder accessed by the world's highest gondola — 14m annual snowfall, 1,500m vertical descents on Apharwat Peak.", description: "Gulmarg is among the world's great powder ski destinations — 14m+ annual snowfall, the world's highest gondola-served skiing (4,000m), and 1,500m vertical descents of untouched powder. Best for intermediate-to-expert skiers and snowboarders. Guides, equipment rental, and avalanche safety training available. Season: December to March.", images: [], duration: "Full day", difficulty: "Advanced", bestSeason: "December to March", destSlug: "gulmarg", metaTitle: "Gulmarg Powder Skiing — Himalayan Ski Resort at 4,000m", metaDescription: "Powder skiing in Gulmarg: world's highest gondola, 1,500m vertical, 14m snowfall. Guided ski packages. Book with Asgari Tours.", featured: true, order: 3 },
  { slug: "pony-trek-baisaran", title: "Pony Trek to Baisaran & Betaab Valley", category: "adventure", shortDescription: "Ride a pony through pine forests to the green meadows of Baisaran and the picture-perfect Betaab Valley along the Lidder River.", description: "Pony treks from Pahalgam wind through pine forests to the rolling green meadow of Baisaran ('mini Switzerland') and onward to the iconic Betaab Valley where the Lidder river runs turquoise. Suitable for families and non-trekkers. The ponies are led by experienced handlers. Duration 3-5 hours depending on route.", images: [], duration: "3-5 hours", difficulty: "Easy", bestSeason: "April to October", destSlug: "pahalgam", metaTitle: "Pony Trek in Pahalgam — Baisaran & Betaab Valley", metaDescription: "Pony rides in Pahalgam to Baisaran meadows and Betaab Valley. Family-friendly. Book with Asgari Tour & Travels.", featured: false, order: 4 },
  { slug: "wazwan-cooking-class", title: "Wazwan Cooking Class with a Master Waza", category: "cultural", shortDescription: "Learn to cook the legendary 36-course Kashmiri Wazwan feast — Rogan Josh, Gushtaba, Rista — with a traditional master chef.", description: "The Wazwan is Kashmir's grand ceremonial feast, traditionally 36 courses prepared overnight by a waza (master chef). In this hands-on class, you'll learn to make signature dishes: Rogan Josh (fiery red lamb), Gushtaba (meatballs in yogurt gravy), Rista (meatballs in saffron gravy), and Tabak Maaz (fried lamb ribs). Includes the full meal you helped cook. Duration 4-5 hours.", images: [], duration: "4-5 hours", difficulty: "Easy", bestSeason: "Year-round", destSlug: "srinagar", metaTitle: "Wazwan Cooking Class in Srinagar — Learn Kashmiri Cuisine", metaDescription: "Hands-on Wazwan cooking class with a master waza. Learn Rogan Josh, Gushtaba, Rista. Includes the feast. Book with Asgari Tours.", featured: true, order: 5 },
  { slug: "thajiwas-glacier-trek", title: "Trek to Thajiwas Glacier, Sonmarg", category: "adventure", shortDescription: "Trek or ride a pony to the Thajiwas Glacier — a stunning ice field just above Sonmarg, accessible from May to September.", description: "The Thajiwas Glacier sits just 3km above Sonmarg and is accessible by a short trek or pony ride through alpine meadows. The glacier retains its ice year-round and offers dramatic views of the surrounding peaks. Ponies and guides available at the base. Duration 3-4 hours round trip. Best May-September when the road to Sonmarg is open.", images: [], duration: "3-4 hours", difficulty: "Moderate", bestSeason: "May to September", destSlug: "sonmarg", metaTitle: "Thajiwas Glacier Trek from Sonmarg — Pony & Walking", metaDescription: "Trek or pony ride to Thajiwas Glacier above Sonmarg. Alpine meadows, ice fields. Book with Asgari Tour & Travels.", featured: false, order: 6 },
  { slug: "pangong-overnight-camp", title: "Overnight Camp at Pangong Lake", category: "nature", shortDescription: "Spend a night beside the surreal blue Pangong Tso at 4,350m — stargazing under one of the clearest skies on Earth.", description: "Pangong Tso at 4,350m is among the world's most spectacular high-altitude lakes. An overnight stay at a tented camp in Spangmik lets you experience the lake's colour shifts from sapphire to turquoise through the day, and the Milky Way in stunning clarity at night. Tented camps have beds, blankets, and basic meals. Requires acclimatization in Leh first.", images: [], duration: "1 night", difficulty: "Moderate", bestSeason: "May to September", destSlug: "pangong-tso", metaTitle: "Overnight Camping at Pangong Lake Ladakh — Stargazing", metaDescription: "Spend a night at Pangong Tso (4,350m). Colour shifts, Milky Way, tented camp. Book with Asgari Tour & Travels.", featured: true, order: 7 },
  { slug: "bactrian-camel-ride", title: "Bactrian Camel Ride on Nubra Dunes", category: "adventure", shortDescription: "Ride a double-humped Bactrian camel across the sand dunes of Hunder in Nubra Valley — a Silk Route remnant.", description: "The sand dunes of Hunder in Nubra Valley are home to double-humped Bactrian camels — descendants of the Silk Route caravan trade. A camel ride across the dunes at sunset, with snow-capped peaks in the background, is a surreal experience found nowhere else in India. Rides last 30-60 minutes. Accessible via Khardung La, May-September.", images: [], duration: "30-60 min", difficulty: "Easy", bestSeason: "May to September", destSlug: "nubra-valley", metaTitle: "Bactrian Camel Ride in Nubra Valley — Hunder Dunes", metaDescription: "Double-humped Bactrian camel ride on Hunder sand dunes, Nubra Valley. Silk Route experience. Book with Asgari Tours.", featured: false, order: 8 },
  { slug: "monastery-morning-prayers", title: "Dawn Prayers at Thiksey Monastery", category: "cultural", shortDescription: "Witness the hypnotic dawn chanting and morning prayers at Thiksey — Ladakh's Potala-like 12-tier monastery.", description: "Thiksey Monastery, resembling Lhasa's Potala Palace, hosts dawn prayers around 7am where monks chant in deep, resonant tones accompanied by drums and horns. The experience is hypnotic and spiritual — arrive by 6:45am. The monastery also houses a 15m Maitreya Buddha statue. Photography permitted in the courtyard; ask before photographing inner halls.", images: [], duration: "1-2 hours", difficulty: "Easy", bestSeason: "May to October", destSlug: "thiksey-monastery", metaTitle: "Thiksey Monastery Morning Prayers — Dawn Chanting", metaDescription: "Witness dawn prayers at Thiksey Monastery, Ladakh. Hypnotic chanting, 15m Maitreya Buddha. Book with Asgari Tours.", featured: false, order: 9 },
  { slug: "saffron-harvest-pampore", title: "Saffron Harvest Experience in Pampore", category: "cultural", shortDescription: "Join the autumn saffron harvest in Pampore — pick the world's most expensive spice at source, October-November only.", description: "Pampore, 15km from Srinagar, is the saffron capital of India. In October-November, the purple crocus flowers bloom and local families harvest the precious red stigmas by hand. Visitors can join the harvest, learn how saffron is graded, and buy directly from the growers at source prices. The fields turn purple in peak bloom — a photographer's dream.", images: [], duration: "2-3 hours", difficulty: "Easy", bestSeason: "October to November", destSlug: "srinagar", metaTitle: "Saffron Harvest in Pampore, Kashmir — Autumn Experience", metaDescription: "Join the saffron harvest in Pampore. Pick the world's most expensive spice at source. October-November. Book with Asgari Tours.", featured: false, order: 10 },
  { slug: "tarsar-marsar-trek", title: "Tarsar Marsar Lakes Trek (3 days)", category: "adventure", shortDescription: "A 3-day alpine trek connecting the twin cobalt-blue lakes of Tarsar and Marsar above Aru — meadows, wildflowers, and shepherd camps.", description: "The Tarsar Marsar Trek is a 3-day point-to-point trek above the Lidder Valley connecting two alpine lakes. Tarsar (3,795m) is the camp base; Marsar sits across a 4,000m ridge. The trail crosses wildflower meadows in July, passes shepherd camps with grazing flocks, and offers dawn reflections on the lakes. Requires a licensed guide and porters. Start/end: Aru Valley (12km from Pahalgam).", images: [], duration: "3 days", difficulty: "Moderate", bestSeason: "July to September", destSlug: "tarsar-marsar-lakes", metaTitle: "Tarsar Marsar Lakes Trek — 3-Day Kashmir Alpine Trek", metaDescription: "3-day Tarsar Marsar trek: twin alpine lakes, wildflower meadows, shepherd camps. From Aru Valley. Book with Asgari Tours.", featured: true, order: 11 },
  { slug: "houseboat-stay-dal-lake", title: "Heritage Houseboat Stay on Dal Lake", category: "leisure", shortDescription: "Spend a night on a carved-wood heritage houseboat on Dal Lake — an experience found nowhere else on Earth.", description: "Staying on a traditional Kashmiri houseboat is a once-in-a-lifetime experience. These carved-wood floating homes date to the British era and are moored along Dal and Nagin Lakes. Each houseboat has 2-4 bedrooms with attached baths, a sitting-dining room, and a sun deck. Includes Kahwa (saffron tea) welcome, home-cooked Kashmiri meals, and a complimentary sunset shikara ride.", images: [], duration: "1+ nights", difficulty: "Easy", bestSeason: "April to October (year-round)", destSlug: "dal-lake", metaTitle: "Heritage Houseboat Stay on Dal Lake Srinagar", metaDescription: "Stay overnight on a carved-wood Kashmiri houseboat on Dal Lake. Unique experience, home-cooked meals. Book with Asgari Tours.", featured: true, order: 12 },
  { slug: "mughal-gardens-walk", title: "Mughal Gardens Heritage Walk", category: "cultural", shortDescription: "Walk the 17th-century Persian 'chahar bagh' gardens — Nishat, Shalimar, Chashme Shahi & Pari Mahal — with a heritage guide.", description: "Srinagar's Mughal Gardens are UNESCO-quality Persian gardens built by Mughal emperors Jahangir and Shah Jahan in the 17th century. This guided walk covers Nishat Bagh (12 terraces), Shalimar Bagh (the most romantic), Chashme Shahi (spring-fed), and Pari Mahal (hilltop observatory). Learn the chahar bagh design, the symbolism of water channels, and the stories behind each garden. Duration 3-4 hours.", images: [], duration: "3-4 hours", difficulty: "Easy", bestSeason: "March to October (April for tulips)", destSlug: "mughal-gardens", metaTitle: "Mughal Gardens Heritage Walk in Srinagar — Guided Tour", metaDescription: "Guided walk through Srinagar's Mughal Gardens: Nishat, Shalimar, Chashme Shahi, Pari Mahal. Persian chahar bagh. Book with Asgari Tours.", featured: false, order: 13 },
  { slug: "indus-river-rafting", title: "White Water Rafting on the Indus River", category: "adventure", shortDescription: "Raft the legendary Indus River through Ladakh's dramatic gorges — grade II-IV rapids with mountain scenery.", description: "White water rafting on the Indus (Sindhu) River in Ladakh offers grade II-IV rapids through dramatic mountain gorges, with scenery ranging from barren moonscapes to green oases. Popular stretches include Phey to Nimo (grade II-III, 2-3 hours) and the more challenging runs near Chilling. No prior experience needed for grade II-III. May-September only. Includes guide, equipment, and transport.", images: [], duration: "2-3 hours", difficulty: "Moderate", bestSeason: "June to September", destSlug: "leh", metaTitle: "Indus River Rafting in Ladakh — White Water Rapids", metaDescription: "White water rafting on the Indus River in Ladakh. Grade II-IV rapids, mountain gorges. No experience needed. Book with Asgari Tours.", featured: false, order: 14 },
  { slug: "astrophotography-hanle", title: "Astrophotography at Hanle Dark Sky Reserve", category: "nature", shortDescription: "Photograph the Milky Way from one of the world's best dark-sky sites at 4,500m in Hanle, Ladakh.", description: "Hanle, in the remote eastern Changthang plateau, is home to the Indian Astronomical Observatory at 4,500m — one of the highest observatories in the world, chosen for its exceptionally dark, dry, and cloudless skies. The Milky Way is visible naked-eye. Astrophotography sessions are led by local guides who know the best foregrounds (monastery, observatory dome, nomad tents). Requires a special permit. Best April-September.", images: [], duration: "1 night", difficulty: "Moderate", bestSeason: "April to September", destSlug: "hanle", metaTitle: "Astrophotography at Hanle Ladakh — Milky Way Dark Sky", metaDescription: "Milky Way astrophotography at Hanle (4,500m), one of the world's best dark-sky sites. Guided sessions. Book with Asgari Tours.", featured: true, order: 15 },
]

async function main() {
  console.log("🎯 Seeding 15 activities...")
  for (const a of activities) {
    const { destSlug, ...data } = a
    const exists = await db.activity.findUnique({ where: { slug: data.slug } })
    if (exists) { console.log(`  skip ${data.slug}`); continue }
    const destinationId = await destId(destSlug!)
    await db.activity.create({
      data: {
        ...data,
        images: JSON.stringify(data.images),
        destinationId,
        status: "published",
      } as any,
    })
    console.log(`  ✓ ${data.slug}`)
  }
  const count = await db.activity.count()
  console.log(`\nTotal activities: ${count}`)
}

main().catch(console.error).finally(() => db.$disconnect())
